version: '3.8'

services:
  gulp:
    image: node:22
    container_name: gulp_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "npm install && npm run server-start"
    ports:
      - "7000:7000"
      - "35729:35729"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
